GET https://webshop-backend-i8ee.onrender.com


### test de datos por query
POST http://localhost:1234/users/login
Content-Type: application/json

{
  "email": "cruzmlathulerie@gmail.com",
  "password": "1234"
}

### Test prod
POST http://localhost:1234/users/login
Content-Type: application/json

{
  "email": "cruzmlathulerie@gmail.com",
  "password": "1234"
}

### test de autenticación de datos
GET http://localhost:1234/users/protected?type=a

### test de registro de usuario
POST http://localhost:1234/users/register
Content-Type: application/json

{
  "user_name" : "M4Uu",
  "email_address" : "cruzmlathulerie@gmail.com",
  "first_name" : "Cruz",
  "last_name" : "Lathulerie",
  "pswd": "1234"
}

### Test de cambio de datos de usuario
PATCH http://localhost:1234/users/upload
Content-Type: application/json

{
  "user_id" : "7d577e95-5437-11ef-8b6f-7440bb5683fe",
  "user_name" : "M4Uu",
  "email_address" : "cruzmlathulerie@gmail.com",
  "first_name" : "Cruz",
  "last_name" : "Lathulerie",
  "pswd": "1234"
}