
#@M4Uu
### DEVs
@API_URL_DEV = http://localhost:3312/api/

###-----------------------------------------USUARIOS------------------------------------------------------------###
###
POST {{API_URL_DEV}}users/login
Content-Type: application/json

{
  "correo": "cruzmlathulerie@gmail.com",
  "credencial": "123"
}

### test de autenticación de datos
GET {{API_URL_DEV}}users/protected

### test de registro de usuario
POST {{API_URL_DEV}}users/register
Content-Type: application/json

  {
    "cedula" : 29643469,
    "nombres" : "Cruz María Lathulerie Gonzáles",
    "nombre_usuario" : "M4Uu",
    "credencial" : "1234567",
    "localidad" : "Villa Icabarú, Puerto Ordaz, estdo Bolívar",
    "correo" : "cruzmlathulerie@gmail.com",
    "imagen_url" : "https://images.steamusercontent.com/ugc/2041861391656391717/573638A641371D8C177FD8EA7BBA5390F358258D/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true"
  }

### Test de cambio de datos de usuario
PATCH {{API_URL_DEV}}users/update
Content-Type: application/json

{
  "cedula": 29643469,
  "nombres" : "Cruz María Lathulerie Gonzáles",
  "nombre_usuario" : "M4Uu",
  "localidad" : "Villa Icabarú, Puerto Ordaz, Estdo Bolívar",
  "correo" : "cruzmlathulerie@gmail.com"
}
### Test de cambio de datos de usuario (Pago Móvil)
PATCH {{API_URL_DEV}}users/updatemovil
Content-Type: application/json

{
  "cedula": 29643469,
  "telefono": "0412-9999999",
  "banco_num": 120
}

### Test: Obtener datos bancarios
POST {{API_URL_DEV}}users/getmovil
Content-Type: application/json

{
  "cedula": 29643469
}

### Test: Obtener datos de bancos (Nombres y códigos)
get {{API_URL_DEV}}toolkit/listbanks

### Test: Probando enpoint de Storj
get https://link.storjshare.io/s/jwto3t44gmq7snmhq7y6ucpsjksq/tesis-webshop-bucket

### Test: Consulta de roles a un usuario
post {{API_URL_DEV}}users/getroles
Content-Type: application/json

{
  "cedula": 29643469
}

### Test: Obtener datos de usuarios
get {{API_URL_DEV}}users/getusers

### Test: Cambiar administrador en usuario
post {{API_URL_DEV}}users/toggleadmin
Content-Type: application/json

{
  "cedula": 29643469
}

### Test: cambiar estado de usuario
post {{API_URL_DEV}}users/togglstatus
Content-Type: application/json

{
  "cedula": 29643469
}

### Test: Verificar si un usuario está activo
post {{API_URL_DEV}}users/isactive
Content-Type: application/json

{
  "cedula": 29643469
}


###-----------------------------------------VENTAS------------------------------------------------------------###
### Test: Obtener todas las ventas
get {{API_URL_DEV}}ventas/

### Test: Obtener ventas por cédula
post {{API_URL_DEV}}ventas/get
Content-Type: application/json

{
  "cedula": 29643469
}

###-----------------------------------------PRODUCTOS------------------------------------------------------------###
### Test: Obtener todos los productos
get {{API_URL_DEV}}productos

### Test: Obtener un producto por ID
POST {{API_URL_DEV}}productos/get
Content-Type: application/json

{
  "cedula": 29643469,
  "id_producto": 10
}


### Test: Obtener productos por categoría
POST {{API_URL_DEV}}productos/catalogo
Content-Type: application/json

{
  "cedula": 29643469
}


###-----------------------------------------CARRITO------------------------------------------------------------###

### Test: Obtener todos los productos del carrito
post {{API_URL_DEV}}carrito
Content-Type: application/json

{
  "cedula": 29643469
}

### Test: Insertar un producto al carrito
post {{API_URL_DEV}}carrito/insertar
Content-Type: application/json

{
  "cedula": 29643469,
  "id_producto": 1
}

### Test: Eliminar producto del carrito
post {{API_URL_DEV}}carrito/eliminar
Content-Type: application/json

{
  "cedula": 29643469,
  "id_producto": 1
}

###-----------------------------------------GUARDADOS------------------------------------------------------------###
post {{API_URL_DEV}}guardados
Content-Type: application/json

{
  "cedula": 29643469
}

### Test: Guardar un Producto
post {{API_URL_DEV}}guardados/insertar
Content-Type: application/json

{
  "cedula": 29643469,
  "producto_id": 1
}

### Test: Eliminar un producto de los guardados
post {{API_URL_DEV}}guardados/eliminar
Content-Type: application/json

{
  "cedula": 29643469,
  "producto_id": 1
}

###-----------------------------------------PEDIDOS------------------------------------------------------------###
### Test: Todos los pedidos
get {{API_URL_DEV}}pedidos

### Test: Obtener lista de estados
get {{API_URL_DEV}}pedidos/prioridad

### Test:Pedidos por cedula
post {{API_URL_DEV}}pedidos/get
Content-Type: application/json

{
  "cedula": 29643469
}

### Test:Pedidos por id
post {{API_URL_DEV}}pedidos/id
Content-Type: application/json

{
  "pedido_id": 1
}